CREATE TABLE gwr_buildings (
	EGID bigint NOT NULL, 
	GDEKT text NOT NULL, 
	GGDENR bigint NOT NULL, 
	GGDENAME text NOT NULL, 
	EGRID text, 
	LGBKR bigint, 
	LPARZ text, 
	LPARZSX text, 
	LTYP bigint, 
	GEBNR text, 
	GBEZ text, 
	GKODE numeric(12,3), 
	GKODN numeric(12,3), 
	GKSCE bigint, 
	GSTAT bigint, 
	GKAT bigint, 
	GKLAS bigint, 
	GBAUJ bigint, 
	GBAUM bigint,
	GBAUP bigint, 
	GABBJ bigint,
	GAREA bigint, 
	GVOL bigint,
	GVOLNORM bigint,
	GVOLSCE bigint,
	GASTW bigint, 
	GANZWHG bigint, 
	GAZZI bigint, 
	GSCHUTZR bigint, 
	GEBF bigint, 
	GWAERZH1 bigint, 
	GENH1 bigint, 
	GWAERSCEH1 bigint, 
	GWAERDATH1 DATE, 
	GWAERZH2 bigint, 
	GENH2 bigint, 
	GWAERSCEH2 bigint, 
	GWAERDATH2 DATE, 
	GWAERZW1 bigint, 
	GENW1 bigint, 
	GWAERSCEW1 bigint, 
	GWAERDATW1 DATE, 
	GWAERZW2 bigint, 
	GENW2 bigint, 
	GWAERSCEW2 bigint, 
	GWAERDATW2 DATE, 
	GEXPDAT DATE NOT NULL
);
